"""agregar_activo_a_usuarios

Revision ID: 5ba80c9468f5
Revises: 12930077117c
Create Date: 2026-03-31 00:24:54.282056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba80c9468f5'
down_revision: Union[str, Sequence[str], None] = '12930077117c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar activo como nullable con default True
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.execute("UPDATE usuarios SET activo = TRUE WHERE activo IS NULL")
    op.alter_column('usuarios', 'activo', nullable=False)
    
    # Cambio de tamaño en perfiles.nombre
    op.alter_column('perfiles', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'activo')
    op.alter_column('perfiles', 'nombre',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
